# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed7f1ef1772f730a0bbd782926fdd3b1"
name = "auction-pos"
handle = "auction-25"
application_url = "https://mutual-splendid-quagga.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-e386445c.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://mutual-splendid-quagga.ngrok-free.app/auth/callback",
  "https://mutual-splendid-quagga.ngrok-free.app/auth/shopify/callback",
  "https://mutual-splendid-quagga.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
